const Personas = [
  {
    name: "Arsène",
    level: 1,
    arcana: "Fool",
    image: "/Arsène.png",
    price: 1000,
  },
  {
    name: "Raoul",
    level: 76,
    arcana: "Fool",
    image: "/Raoul.png",
    price: 125000,
  },
  {
    name: "Izanagi",
    level: 20,
    arcana: "Fool",
    image: "/Izanagi.png",
    price: 20000,
  },
  {
    name: "Orpheus",
    level: 26,
    arcana: "Fool",
    image: "/Orpheus.png",
    price: 15000,
  },
  {
    name: "Athena",
    level: 60,
    arcana: "Chariot",
    image: "/Athena.png",
    price: 55000,
  },
  {
    name: "Thanatos",
    level: 64,
    arcana: "Death",
    image: "/Thanatos.png",
    price: 100000,
  },
  {
    name: "Messiah",
    level: 81,
    arcana: "Judgement",
    image: "/Messiah.png",
    price: 180000,
  },
  {
    name: "Kaguya",
    level: 16,
    arcana: "Moon",
    image: "/Kaguya.png",
    price: 25000,
  },
  {
    name: "Tsukiyomi",
    level: 50,
    arcana: "Moon",
    image: "/Tsukiyomi.png",
    price: 55000,
  },
  {
    name: "Magatsu-Izanagi",
    level: 44,
    arcana: "Tower",
    image: "/Magatsu-Izanagi.png",
    price: 55000,
  },
  {
    name: "Izanagi-no-Okami",
    level: 80,
    arcana: "World",
    image: "/Izanagi-no-Okami.png",
    price: 200000,
  },
  {
    name: "Ariadne",
    level: 30,
    arcana: "Fortune",
    image: "/Ariadne.png",
    price: 55000,
  },
  {
    name: "Asterius",
    level: 56,
    arcana: "Fortune",
    image: "/Asterius.png",
    price: 75000,
  },
  {
    name: "Metatron",
    level: 89,
    arcana: "Justice",
    image: "/Metatron.png",
    price: 120000,
  },
  {
    name: "Lucifer",
    level: 93,
    arcana: "Star",
    image: "/Lucifer.png",
    price: 180000,
  },
  {
    name: "Satan",
    level: 92,
    arcana: "Judgement",
    image: "/Satan.png",
    price: 150000,
  },
  {
    name: "Michael",
    level: 87,
    arcana: "Judgement",
    image: "/Michael.png",
    price: 150000,
  },
  {
    name: "Alice",
    level: 83,
    arcana: "Death",
    image: "/Alice.png",
    price: 150000,
  },
  {
    name: "Satanael",
    level: 95,
    arcana: "Fool",
    image: "/Satanael.png",
    price: 200000,
  },
  {
    name: "Yoshitsune",
    level: 95,
    arcana: "Fool",
    image: "/Yoshitsune.png",
    price: 200000,
  },
];

export {Personas}