const Personas = [
  {
    name: "Arsène",
    level: 1,
    arcana: "Fool",
    image: "",
    moves: [],
  },
  {
    name: "Raoul",
    level: 76,
    arcana: "Fool",
    image: "",
    moves: [],
  },
  {
    name: "Izanagi",
    level: 20,
    arcana: "Fool",
    image: "",
    moves: [],
  },
  {
    name: "Izanagi Picaro",
    level: 23,
    arcana: "Fool",
    image: "",
    moves: [],
  },
  {
    name: "Orpheus",
    level: 26,
    arcana: "Fool",
    image: "",
    moves: [],
  },
  {
    name: "Orpheus Picaro",
    level: 29,
    arcana: "Fool",
    image: "",
    moves: [],
  },
  {
    name: "Orpheus F",
    level: 11,
    arcana: "Fool",
    image: "",
    moves: [],
  },
  {
    name: "Orpheus F Picaro",
    level: 13,
    arcana: "Fool",
    image: "",
    moves: [],
  },
  {
    name: "Athena",
    level: 60,
    arcana: "Chariot",
    image: "",
    moves: [],
  },
  {
    name: "Athena Picaro",
    level: 62,
    arcana: "Chariot",
    image: "",
    moves: [],
  },
  {
    name: "Thanatos",
    level: 64,
    arcana: "Death",
    image: "",
    moves: [],
  },
  {
    name: "Thanatos Picaro",
    level: 69,
    arcana: "Death",
    image: "",
    moves: [],
  },
  {
    name: "Messiah",
    level: 81,
    arcana: "Judgement",
    image: "",
    moves: [],
  },
  {
    name: "Messiah Picaro",
    level: 90,
    arcana: "Judgement",
    image: "",
    moves: [],
  },
  {
    name: "Kaguya",
    level: 16,
    arcana: "Moon",
    image: "",
    moves: [],
  },
  {
    name: "Kaguya Picaro",
    level: 25,
    arcana: "Moon",
    image: "",
    moves: [],
  },
  {
    name: "Tsukiyomi",
    level: 50,
    arcana: "Moon",
    image: "",
    moves: [],
  },
  {
    name: "Tsukiyomi Picaro",
    level: 55,
    arcana: "Moon",
    image: "",
    moves: [],
  },
  {
    name: "Magatsu-Izanagi",
    level: 44,
    arcana: "Tower",
    image: "",
    moves: [],
  },
  {
    name: "Magatsu-Izanagi Picaro",
    level: 48,
    arcana: "Tower",
    image: "",
    moves: [],
  },
  {
    name: "Izanagi-no-Okami",
    level: 80,
    arcana: "World",
    image: "",
    moves: [],
  },
  {
    name: "Izanagi-no-Okami Picaro",
    level: 89,
    arcana: "World",
    image: "",
    moves: [],
  },
  {
    name: "Ariadne",
    level: 30,
    arcana: "Fortune",
    image: "",
    moves: [],
  },
  {
    name: "Ariadne Picaro",
    level: 42,
    arcana: "Fortune",
    image: "",
    moves: [],
  },
  {
    name: "Asterius",
    level: 56,
    arcana: "Fortune",
    image: "",
    moves: [],
  },
  {
    name: "Asterius Picaro",
    level: 62,
    arcana: "Fortune",
    image: "",
    moves: [],
  },
  {
    name: "Metatron",
    level: 89,
    arcana: "Justice",
    image: "",
    moves: [],
  },
  {
    name: "Lucifer",
    level: 93,
    arcana: "Star",
    image: "",
    moves: [],
  },
  {
    name: "Satan",
    level: 92,
    arcana: "Judgement",
    image: "",
    moves: [],
  },
  {
    name: "Michael",
    level: 87,
    arcana: "Judgement",
    image: "",
    moves: [],
  },
  {
    name: "Alice",
    level: 83,
    arcana: "Death",
    image: "",
    moves: [],
  },
  {
    name: "Satanael",
    level: 95,
    arcana: "Fool",
    image: "",
    moves: [],
  },
  {
    name: "Yoshitsune",
    level: 95,
    arcana: "Fool",
    image: "",
    moves: [],
  },
];

export { Personas };

Personas.forEach((persona) => {
  console.log(persona.name);
});
