const personas = [
  {
    name: "Arsène",
    arcana: "Fool",
    price: 0,
    stats: {
      strength: 10,
      magic: 12,
      endurance: 10,
      agility: 11,
      luck: 9,
    },
    image: "",
  },
  {
    name: "Jack Frost",
    arcana: "Fool",
    price: 5000,
    stats: {
      strength: 8,
      magic: 15,
      endurance: 7,
      agility: 12,
      luck: 10,
    },
    image: "",
  },
  {
    name: "Pixie",
    arcana: "Lovers",
    price: 4000,
    stats: {
      strength: 6,
      magic: 14,
      endurance: 7,
      agility: 10,
      luck: 11,
    },
    image: "",
  },
  {
    name: "Bicorn",
    arcana: "Chariot",
    price: 5500,
    stats: {
      strength: 10,
      magic: 11,
      endurance: 10,
      agility: 9,
      luck: 8,
    },
    image: "",
  },
  {
    name: "Oberon",
    arcana: "Emperor",
    price: 9000,
    stats: {
      strength: 14,
      magic: 12,
      endurance: 13,
      agility: 11,
      luck: 9,
    },
    image: "",
  },
  {
    name: "Yoshitsune",
    arcana: "Tower",
    price: 15000,
    stats: {
      strength: 18,
      magic: 10,
      endurance: 15,
      agility: 14,
      luck: 10,
    },
    image: "",
  },
  {
    name: "Sraosha",
    arcana: "Star",
    price: 12000,
    stats: {
      strength: 16,
      magic: 13,
      endurance: 14,
      agility: 12,
      luck: 10,
    },
    image: "",
  },
  {
    name: "Satan",
    arcana: "Judgement",
    price: 14000,
    stats: {
      strength: 17,
      magic: 14,
      endurance: 15,
      agility: 11,
      luck: 12,
    },
    image: "",
  },
  {
    name: "Fafnir",
    arcana: "Hermit",
    price: 13000,
    stats: {
      strength: 15,
      magic: 12,
      endurance: 14,
      agility: 10,
      luck: 11,
    },
    image: "",
  },
  {
    name: "Setanta",
    arcana: "Chariot",
    price: 7000,
    stats: {
      strength: 13,
      magic: 9,
      endurance: 10,
      agility: 12,
      luck: 10,
    },
    image: "",
  },
  {
    name: "Shiki-Ouji",
    arcana: "Chariot",
    price: 11000,
    stats: {
      strength: 15,
      magic: 12,
      endurance: 13,
      agility: 11,
      luck: 10,
    },
    image: "",
  },
  {
    name: "Saki Mitama",
    arcana: "Fortune",
    price: 8000,
    stats: {
      strength: 12,
      magic: 12,
      endurance: 11,
      agility: 11,
      luck: 14,
    },
    image: "",
  },
  {
    name: "Kaguya",
    arcana: "Moon",
    price: 11000,
    stats: {
      strength: 12,
      magic: 16,
      endurance: 10,
      agility: 10,
      luck: 12,
    },
    image: "",
  },
  {
    name: "Ame-no-Uzume",
    arcana: "Lovers",
    price: 9000,
    stats: {
      strength: 9,
      magic: 15,
      endurance: 9,
      agility: 13,
      luck: 10,
    },
    image: "",
  },
  {
    name: "Norn",
    arcana: "Fortune",
    price: 14000,
    stats: {
      strength: 15,
      magic: 14,
      endurance: 13,
      agility: 12,
      luck: 11,
    },
    image: "",
  },
  {
    name: "Hecatoncheires",
    arcana: "Tower",
    price: 16000,
    stats: {
      strength: 20,
      magic: 12,
      endurance: 18,
      agility: 10,
      luck: 9,
    },
    image: "",
  },
];
